### ISSUE TITLE
polyesterhat/Tripwire

### ISSUE THREAD

**Issue by szepeviktor** [lucanos/Tripwire#10]
Please consider merging https://github.com/polyesterhat/Tripwire
It is very high quality code.

**Comment by lucanos** [comment]
The work done by Polyesterhat is nice, but it is definitely a step away from the simplicity of the original Tripwire. The intent was to create a single PHP file which could be simply deployed anywhere and triggered easily. Polyesterhat's code is much more complex, involving multiple files and directories, all for the same net effect.

I may look at spinning this into Tripwire Lite and Tripwire Pro or something at a  later stage, but at the moment, simplicity is key.

**Comment by szepeviktor** [comment]
I understand what you are meaning.
I consider putting all in one file.
