### ISSUE TITLE
How to exclude a directory?

### ISSUE THREAD

**Issue by ghost** [lucanos/Tripwire#12]
What is the best way to exclude a directory?

Thanks!

**Comment by madahmani** [comment]
hmm, is that even possible? to exclude a whole directory?

**Comment by ghost** [comment]
I think we could just add another array listing directories to exclude.  An if statement using pathinfo and dirname should do the trick.

If not already written I can try to whip something up and submit a pull request.

**Comment by madahmani** [comment]
that might be a good idea indeed.

**Comment by madahmani** [comment]
what do you say about this then!

```
// Excluded File/Folder
    if( $f1 = in_array( $entry , $config['exclude']['files'] )
        || in_array( $entry_full , $config['exclude']['files'] ) ){
      debugMsg( "<td><em>Excluded File/Folder (".array_search( isset( $f1 ) && $f1 ? $entry : $entry_full , $config['exclude']['files'] ).")</em></td></tr>\n" );
      continue;
    }
```

**Comment by madahmani** [comment]
The script already states that: "Within the Configuration Settings, exclusions can be set for any files/folders"

**Comment by ghost** [comment]
Thanks!

**Comment by lucanos** [comment]
@Jedwards-Eric are you happy for me to Close this Issue?

**Comment by ghost** [comment]
Yes sir thanks.

**Comment by lucanos** [comment]
Closing as User Education Issue.
Thanks to @madahmani for helping a fellow user out!
