### ISSUE TITLE
Question: What is the minimum requirement?

### ISSUE THREAD

**Issue by lenamtl** [lucanos/Tripwire#8]
Hi,

What is the minimum requirement? PHP version etc...

Thanks

**Comment by lenamtl** [comment]
I have a few php4 website that I like to monitor.
Let me know if a previous version for php4 exist or similar script that can do the job.

Thanks

**Comment by lucanos** [comment]
@thegeeex: Nice pickup. I will make that change soon.

@lenamtl: Rewriting this script to work for PHP4 would be wasted effort on my part - you are more than welcome to fork it and try and adapt it to that version of PHP, but the absence of some functions may mean a major rewrite would be required. (And, as PHP5 is better and where we should all be going, for security, efficiency and maintainability reasons, adapting it to PHP4 would be a step in the wrong direction.)

**Comment by lucanos** [comment]
@lenamtl: Your other option to manage changes in files, etc. would be to manually download the content of the site, store it in a folder, and then at a later time, download the content from the site again into a second folder and then use a Difference/Merge application like WinMerge or Kaleidoscope to compare the two folders. As was pointed out, this script (in its first version) relies on functions which are not available in PHP4 and to even build a shim to create similar functionality for PHP4 would be alot of work.

**Comment by lenamtl** [comment]
I understand.

I do compare files for now once in a while.
I'm also using FTP, I do a quick check for date of the files.
I cannot do manual check everyday...
This is why I need is to get notified when this occurred at least the same day like your script does.

Thanks for the script this is very helpful.
