### ISSUE TITLE
Problem when using cron job

### ISSUE THREAD

**Issue by lenamtl** [lucanos/Tripwire#9]
Hi,

I'm testing your script live and I'm getting problem when using cron job, the script doesn't act the same as manually.

Working ok:
Yesterday, I did a manual test running manually using the URL 
it's scanning the appropriate files and folders and created the md5 file in the same folder as the script which is located in public_html/

Problem:
Today I did a test with cron job
First I have deleted the md5 file
I use this kind of path for the cron job
/usr/local/bin/php /home/user/domains/mydomain.com/public_html/tripwire.php 
When using this cron job it's scanning all folders and files that are under the main folder 
what I mean by that is same levels as /domains/
you know where mail and backup dir. are located
and it's created also the md5 file in this level /domains/ instead of the same level as the script. 

PS I'm not using the config file and I'm using the latest version of the tripwire.

Any clue how to fix this?
Thanks

**Comment by lucanos** [comment]
The script is designed to be called via a URL. It relies upon that to determine the document root, etc.

Maybe look at modifying your Cronjob to call the script via the URL rather than launching it directly?
http://stackoverflow.com/questions/13259530/using-cron-jobs-to-visit-url

**Comment by lenamtl** [comment]
Ok I will try that tonight  and I will get back to you

Which syntax are you using with cron job?

I was thinking maybe I can add a different path for the md5 file 
and adding folder name to be ignored...
or changing the way it's determine the root...

**Comment by lucanos** [comment]
I tend to call the script directly.

The correct syntax for calling a URL with a cronjob are easily found through a Google search, the link I included in the above comment, or a cPanel section.

**Comment by lenamtl** [comment]
Here is the syntax I'm using with succes :)

```
wget -O - http://www.mysite.com/tripwire.php >/dev/null 2>&1
```

Notes:
`-O`    prevent the php file to get copied each time in the root, otherwise it will create a copy of the php file everytime the script run.

`>/dev/null 2>&1`is to prevent receiving an email if something went wrong with the script 
(so add it only when you are sure the script work ok)

**Comment by szepeviktor** [comment]
`wget -qO- http://www.mysite.com/tripwire.php`

To receive an email about what is happening.
